# Generated by Django 4.0.10 on 2023-06-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Sfide',
        ),
    ]
