# Generated by Django 4.0.10 on 2023-07-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sfide',
        ),
    ]
