# Generated by Django 4.0.10 on 2023-07-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_sfide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('photo_link', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
        ),
    ]
