# Generated by Django 4.0.10 on 2023-07-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_challenge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Challenges',
        ),
    ]
