# Generated by Django 4.0.10 on 2023-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_capitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='photo_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
