# Generated by Django 4.0.10 on 2023-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_challenges_photo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='coordinates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='challenges',
            name='long',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
